version: '3.8'

services:
  backend:
    image: ghcr.io/harmohanjohal/msc_research_project-backend:latest
    container_name: heat-prediction-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production

  frontend:
    image: ghcr.io/harmohanjohal/msc_research_project-frontend:latest
    container_name: heat-prediction-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
